# 数组计算二

## 广播 

In [1]:
# 实例1：
import numpy as np
a = np.array([0, 1, 2])
print(a + 5)

[5 6 7]


In [3]:
# 实例2：
m = np.ones((3, 3))
m + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [6]:
# 实例3：
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)
a + b

[0 1 2]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## 广播的规则

- 1. 如果两个数组的维度数不相同，那么小维度数组的形状将会在最左边补1.

- 2. 如果两个数组的形状在任何一个维度上都不匹配，那么数组的形状会沿着维度为1的维度扩展以匹配另外一个数组的形状。

- 3. 如果两个数组的形状在任何一个维度上都不匹配并且没有任何一个维度等于1.那么会引发异常。

### 示例一 

In [7]:
M = np.ones((2, 3))
a = np.arange(3)

分析步骤：
1. 查看数组形状
M.shape = (2, 3)
a.shape = (3,)

2. 根据规则1，数组a的维度数更小，在其左边补1，补1后的形状为：
a.shape = (1, 3)

3. 根据规则2，数组的形状沿着维度数为1的维度扩展，匹配另外一个数组的形状，扩展后的形状为
a.shape = (2, 3)

4. 此时，进行运算
M + a

In [8]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.]])

### 示例二

In [9]:
a = np.arange(3).reshape((3,1))
b = np.arange(3)

分析步骤：

1. 写出两个数组的形状
a.shape = (3, 1)
b.shape = (3,)

2. 根据规则1，数组a的维度数更小，在其左边补1，补1后的形状为： b.shape = (1, 3), a.shape=(3, 1)

3. 根据规则2，数组的形状沿着维度为1的维度扩展，以匹配另一个数组，扩展的数组形状为： a.shape = (3, 3), b.shape = (3, 3)

In [10]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### 示例三

In [11]:
M = np.ones((3, 2))
a = np.arange(3)

分析步骤：

1. 分析数组形状，a.shape = (3,), M.shape = (3, 2)

2. 根据规则1，a的形状必须用1进行补全，M.shape = (3, 2), a.shape = (1, 3);

3. 根据规则2，扩展a的维度为1的维度匹配M的维度, a.shape = (3, 3), M.shape = (3, 2)

**最终形状还是不匹配，因此这两个数组是不兼容的**

In [12]:
M + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [15]:
rand = np.random.RandomState(42)
mean = [0, 0]
cov = [[1, 2],
      [2, 5]]
x = rand.multivariate_normal(mean, cov, 100)
x

array([[-4.05992582e-01, -1.12980900e+00],
       [-1.18122448e+00, -1.20321251e+00],
       [ 3.05929845e-01,  4.85151964e-01],
       [-1.75268695e+00, -3.40069525e+00],
       [ 2.26109036e-01,  1.13313826e+00],
       [ 6.06369182e-01,  9.59802450e-01],
       [ 5.08636661e-01, -8.42962089e-01],
       [ 1.80879440e+00,  3.75820034e+00],
       [ 8.15476694e-01,  2.30887376e+00],
       [ 1.37937009e+00,  1.80142746e+00],
       [-1.26768205e+00, -3.30483370e+00],
       [ 4.82839600e-01, -3.76458413e-01],
       [ 4.60495820e-01,  1.23179700e+00],
       [ 9.19606001e-01,  2.62677788e+00],
       [ 6.66544157e-01,  1.29345291e+00],
       [-1.52931750e-01,  1.63568156e+00],
       [ 4.17238258e-01, -1.37555797e-01],
       [-2.92735771e-01, -2.02815831e+00],
       [ 5.56968489e-01, -7.76490778e-01],
       [ 1.15174837e+00,  2.99364761e+00],
       [-7.47833961e-01, -1.61994320e+00],
       [ 2.22072477e-01,  2.10218094e-01],
       [ 1.64144866e+00,  3.18365385e+00],
       [ 2.

In [18]:
x = np.zeros(10)
i = [2, 3, 3, 4, 4, 4]
print(x[i])
x[i] += 1
print(x[i])
x

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


array([0., 0., 1., 1., 1., 0., 0., 0., 0., 0.])