# NumPy数组的计算

## 1、通用函数

NumPy为很多类型的操作提供了非常方便的、静态类型的、可编译程序的接口，也被称作**向量**操作。可以通过简单地对数组执行操作来实现，这里的对数组的操作会被用于数组中的每一个元素。这种向量方法被用于将循环推送至NumPy之下的编译层，这样会取得更快的执行效率。

NumPy中的向量操作是通过通用函数实现的，通用函数的主要目的是对NumPy数组中的值执行更快的重复操作。通过通用函数用向量的方式进行计算几乎总比用python循环实现的计算更加高效，尤其是当数组很大时。

### 1.1 加、减、乘、除

In [2]:
import numpy as np
x = np.arange(4)
print("x     = ", x)
print("x + 5 = ", x + 5)
print("x - 5 = ", x - 5)
print("x * 2 = ", x * 2)
print("x / 2 = ", x / 2)

x     =  [0 1 2 3]
x + 5 =  [5 6 7 8]
x - 5 =  [-5 -4 -3 -2]
x * 2 =  [0 2 4 6]
x / 2 =  [0.  0.5 1.  1.5]


### 1.2 向下、向上（通用函数中没有，可以使用np.ceil）整除运算 

In [3]:
print("x // 2 = ",x // 2) # 向下整除运算

x // 2 =  [0 0 1 1]


### 1.3 求负

In [4]:
print("-x = ", -x)

-x =  [ 0 -1 -2 -3]


### 1.4 指数运算 **

In [5]:
print("x ** 2 = ", x ** 2)

x ** 2 =  [0 1 4 9]


###  1.5 模运算 %

In [6]:
print("x % 2 = ", x % 2)

x % 2 =  [0 1 0 1]


### 1.6 绝对值 np.absolute、np.abs

In [7]:
x = np.array([-2, -1, 0, 1, 2])
np.absolute(x)

array([2, 1, 0, 1, 2])

In [9]:
print("x         = ", x)
print("np.abs(x) = ", np.abs(x))

x         =  [-2 -1  0  1  2]
np.abs(x) =  [2 1 0 1 2]


该通用函数可以处理复数，处理复数时，返回的是复数的模(magnitude)

In [10]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

### 1.7 三角函数

In [12]:
# 定义一个角度数组
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [16]:
# 三角运算
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [20]:
# 逆三角运算
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### 1.8 指数、对数

In [23]:
x = [1, 2, 3]

# 指数
print("x = ", x)
print("e^x = ", np.exp(x))
print("2^x = ", np.exp2(x))
print("3^x = ", np.power(3, x))

x =  [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3  9 27]


In [26]:
# 对数
x = [1, 2, 4, 10]
print("x        = ", x)
print("ln(x)    = ", np.log(x))
print("log2(x)  = ", np.log2(x))
print("log10(x) = ", np.log10(x))

x        =  [1, 2, 4, 10]
ln(x)    =  [0.         0.69314718 1.38629436 2.30258509]
log2(x)  =  [0.         1.         2.         3.32192809]
log10(x) =  [0.         0.30103    0.60205999 1.        ]


## 2. 通用函数的高级特性

### 2.1 指定输出 

所有的通用函数都可以通过out参数来指定计算结果的存放位置：

In [30]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out = y)
print(y)

[ 0. 10. 20. 30. 40.]


In [31]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


如果这里写的是`y[::2] = 2 ** x`,结果会先创建一个临时数组，该数组存放的是`2 ** x`的结果，然后将这些值复制到y数组中。对于较大的数组，使用out参数，可以有效节约内存。

### 2.2 聚合 

In [32]:
# reduce方法
x =np.arange(1, 6)
np.add.reduce(x)

15

In [33]:
np.multiply.reduce(x)

120

In [34]:
# 使用accumulate存储每次计算的中间结果
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [35]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

### 2.3 外积

In [37]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])